{{- if and .Values.apisix.discovery.enabled (hasKey .Values.apisix.discovery.registry "kubernetes") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.apisix.serviceAccountName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.apisix.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.apisix.serviceAccountName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
